// Define the type for queries object
type QueriesType = {
  [key: string]: string[];
};

// Define your queries object
const queries: QueriesType = {
  "1": [
    "Mở đầu là cảnh người đàn ông áo đang đang nói chuyện với 1 người đang ông lớn tuổi hơn mặc áo sơ mi có sọc ngang.",
    "Người đàn ông áo đen đó đứng bên trái khung hình, có mang kinh và tay mang đồng hồ.",
    "Cảnh tiếp quay một miếu thờ một liệt sĩ ở Thanh Hóa.",
    "Có cảnh một người đang đo chiều dài thân cây bằng thước dây.",
    "L29_V023",
    "[5650, 10775]",
    "QA",
    "https://youtu.be/vgQQe1AS9Y4?t=226",
  ],
  "2": [
    "Một cảnh đua xe đạp, mở đầu là cảnh quay chỉ có 4 người lần lượt theo thứ từ trái qua phải khung hình, mặc áo màu: đỏ (ở tay áo), xanh dương, vàng, và chấm bi đỏ.",
    "Người về đích mặc áo màu xanh dương, có cảnh quay anh ta vừa cán đích và buông cả 2 tay lái.",
    "Về đích sau đó là người áo vàng, 2 người áo đỏ và chấm bi đỏ gần như cùng cán đích ở vị trí thứ 3.",
    "Đây là một cảnh quay khá rõ cả 4 tay đua về đầu tiên, có chữ 'ĐÍCH' đánh dấu đích đến.",
    "L23_V017",
    "[225, 5575]",
    "QA",
    "https://youtu.be/4--VFb1YVBQ?t=816",
  ],
  "3": [
    "Hai người Ấn Độ đang tạo dáng chụp ảnh trước 1 tòa nhà nổi tiếng ở trung tâm Quận 1, TP.HCM.",
    "Cảnh tiếp theo quay 2 xe buýt 2 tầng, 1 chiếc có màu xanh đen, 1 chiếc có màu đỏ.",
    "Một đoàn người mặt áo phao màu cam.",
    "Một đoàn người mặt áo phao màu cam.",
    "L21_V029",
    "[4440, 5575]",
    "QA",
    "https://youtu.be/dlpQXX_hYxk?t=198",
  ],
  "4": [
    "Cảnh quay một con trâu đang đi tới chỗ 2 người đan ông, được biết cảnh quay ở tỉnh Ninh Thuận.",
    "Tiếp theo là cảnh con trâu đó đang gặm cỏ.",
    "Được biết con trâu ăn cỏ từ tay một người đàn ông.",
    "Cảnh tiếp theo chiếu những hình ảnh con trâu bị trết.",
    "L21_V029",
    "[19680, 21510]",
    "QA",
    "https://youtu.be/dlpQXX_hYxk?t=198",
  ],
  "5": [
    "Cảnh quay một con lân màu trắng đang đứng trước những cây cột được đánh số. những số dễ thấy mà không bị che khuất là: 1, 3, 4, 6, 7, 8, 9.",
    "Cảnh tiếp theo ta thấy có 3 người đang cầm các dụng cụ để chơi trống múa lân, trong đó có 1 người đang cầm 2 dùi trống.",
    "Cảnh con lân màu trắng này đang đứng hai chân trên 2 cột số 1 và 3.",
    "Cảnh con lân màu trắng này đang đứng hai chân trên 2 cột số 1 và 3.",
    "L24_V039",
    "[90, 3630]",
    "QA",
    "https://youtu.be/FGSj99AsW98?t=3",
  ],
  "6": [
    "Đây là bài giảng qua truyền hình môn Địa lý, bài học về biểu đồ.",
    "Có cảnh về biểu đồ tròn, chúng ta có thể thấy 5 hình tròn trên bảng.",
    "Tiếp theo là 2 cái biểu đồ miền.",
    "Tiếp theo ta thấy là 2 cái biểu đồ đường.",
    "L25_V007",
    "[2300, 10375]",
    "QA",
    "https://youtu.be/7kvm0E6QNkk?t=92",
  ],
  "7": [
    "Bản tin về thể thao điện tử, có một người thuộc uỷ ban Olympic đang đứng phát biểu.",
    "Có hai đội đến từ Đài Loan đang thi đấu với nhau.",
    "Tiếp đến là hình ảnh đội tuyển Hàn Quốc thi đấu với đội Đài Loan.",
    "Đội Hàn Quốc là nhà vô địch giải đấu này. Đây là giải đấu thuộc bộ môn liên minh huyền thoại.",
    "L02_V017",
    "[26122, 27159]",
    "",
    "https://youtu.be/7kvm0E6QNkk?t=92",
  ],
  "8": [
    "Một người đàn ông đeo kính đang nằm trong quan tài.",
    "Sau đó là cảnh một người phụ nữ đóng nắp quan tài. Người đàn ông trông khá hào hứng và vui vẻ.",
    "Sau đó có cảnh vài người khác nằm trong quan tài và người phụ nữ đóng nắp quan tài.",
    "Người phụ nữ mặc áo màu trắng có hoạ tiết bông hoa.",
    "L16_V030",
    "[12970, 14327]",
    "",
    "https://youtu.be/7kvm0E6QNkk?t=92",
  ],
  "9": [
    "Hai người đang trải nghiệm mô phỏng thi đấu olympic.",
    "Người đàn ông ngồi xe lăn, còn người phụ nữ đang đạp xe",
    "Cả hai người họ đều đang mặc đồ vest. ",
    "Đây là một hoạt động triển lãm chào mừng Olympic 2024.",
    "L13_V027",
    "[23135, 23229]",
    "",
    "https://youtu.be/7kvm0E6QNkk?t=92",
  ],
  "10": [
    "Một phần của bản đồ thế giới, có các nước khu vực Trung Đông và Châu Phi.",
    "Tiếp đến là khu vực biển Hồng Hải.",
    "Có 2 lồng ấp các đứa trẻ sơ sinh.",
    "Trong mỗi lồng có 4 bé sơ sinh. Tiếp đến là cảnh các cô y tá chăm sóc các em.",
    "L03_V020",
    "[27134, 28106]",
    "",
    "https://youtu.be/7kvm0E6QNkk?t=92",
  ],
  "11": [
    "Có 4 đĩa súp màu hồng và 1 đĩa có 4 quả khoai tây.",
    "Một người đàn ông mặc áo lông hồng, đội mũ xanh bưng chén chạy.",
    "Tiếp đến là cảnh nhiều người cầm muỗng gõ vào chén súp.",
    "Cuối cùng, một chén súp được mở nắp và mọi người cùng nhau thử món này",
    "L17_V003",
    "[26224, 26560]",
    "",
    "https://youtu.be/7kvm0E6QNkk?t=92",
  ],
  "12": [
    "cảnh quay trời tuyết trắng xóa có 2 chiếc xe bị tuyết bao phủ.",
    "cảnh ngay sau đó có một biển báo dành cho người khuyết tật.",
    "sau đó là cảnh một chiếc xe bị khuất dưới các cây xơ xác.",
    ".",
    "L08_V016",
    "[13759, 14640]",
    "QA",
    "https://youtu.be/7kvm0E6QNkk?t=92",
  ],
  "13": [
    "cảnh quay một con robot không đầu đang bị bộ.",
    "con robot này mặc áo đen có chữ Unitree.",
    "sau đó có một con robot nhỏ màu trắng đứng vào khung hình.",
    ".",
    "L03_V018",
    "[17038, 17198]",
    "QA",
    "https://youtu.be/7kvm0E6QNkk?t=92",
  ],
  "14": [
    "cảnh một người cầm máy ảnh chụp ảnh một con chó.",
    "con chó mặc áo đỏ và ngồi trên ghế.",
    "sau đó là một con chó đen đeo kính.",
    ".",
    "L05_V006",
    "[25791, 25963]",
    "QA",
    "https://youtu.be/7kvm0E6QNkk?t=92",
  ],
  "15": [
    "cảnh quay các nghệ sĩ hát cải lương chào mừng khai mạc.",
    "các nghệ sĩ mặc đồ vàng, đỏ, đen, trắng và xanh dương.",
    "sau đó là cảnh các nghệ sĩ đó rút kiếm giơ lên trời.",
    ".",
    "L29_V005",
    "[8508, 10417]",
    "QA",
    "https://youtu.be/7kvm0E6QNkk?t=92",
  ],
  "16": [
    "cảnh quay một chiếc xe màu đen đang đi vào hầm màu trắng.",
    "sau đó là cảnh 3 chiếc xe đang đậu,  xe trắng nằm giữa 2 xe xanh.",
    "chiếc xe đen ban đầu có bảng hiệu là 'Tesla'.",
    ".",
    "L08_V001",
    "[29937, 30473]",
    "QA",
    "https://youtu.be/7kvm0E6QNkk?t=92",
  ],
  "17": [
    "cảnh quay một chiếc tên lửa được phóng lên trời từ một chiếc xe tăng.",
    "chiếc tên lửa có chấm đen ở đầu và các sọc caro ở thân.",
    "đây là tên lửa đạn đạo tầm ngắn của Triều Tiên.",
    ".",
    "L14_V021",
    "[28787, 29522]",
    "QA",
    "https://youtu.be/7kvm0E6QNkk?t=92",
  ],
  "18": [
    "Cảnh quay tại một lớp học ở Việt Nam có rất nhiều học sinh, các bàn học được xếp thành hình tròn hoặc hình chữ nhật.",
    "Sau đó là cảnh quay thầy giáo kế bên máy chiếu, đang hướng dẫn cách đánh giá học online.",
    "Sau đó là cảnh quay 6 học sinh đang ngồi quanh chiếc bàn tròn, trong đó 4 nam và 2 nữ.",
    "Được biết đây là trường THPT Nguyễn Thị Minh Khai ở TP.HCM.",
    "L02_V020",
    "[3535, 3785]",
    "QA",
    "https://youtu.be/7kvm0E6QNkk?t=92",
  ],
  "19": [
    "Đây là một buổi họp nhiều người, có một phụ nữ đang đứng phát biểu ở góc phải, phía sau là hoa vàng.",
    "Được biết đây là cuộc họp Đề xuất nước mắm là di sản văn hóa phi vật thể, có banner 'Nước mắm Việt nâng tầm ẩm thực Việt'.",
    "Sau đó là cảnh quay cận cảnh người phụ nữ đang phát biểu.",
    "Sau đó là cảnh quay 3 người đàn ông đang ngồi ở bàn đại biểu, trong đó 2 người tóc bạc và một người tóc đen.",
    "L02_V026",
    "[7773, 7966]",
    "QA",
    "https://youtu.be/7kvm0E6QNkk?t=92",
  ],
  "20": [
    "Cảnh cây thông làm từ nón lá tại Vũng Tàu.",
    "Có nón lá màu trắng và nón lá cờ Việt Nam",
    "Sau đó là cảnh quay phỏng vấn người phụ nữ mặc áo đỏ.",
    "Sau đó là cảnh quay phỏng vấn người du khách Canada mặc áo ông già Noel.",
    "L02_V026",
    "[4765, 5087]",
    "QA",
    "https://youtu.be/7kvm0E6QNkk?t=92",
  ],
  "21": [
    "Cảnh quay một chiếc xe buýt màu trắng có chữ TIER IV.",
    "Trước đó là cảnh cây một chiếc xe buýt màu xanh da trời và hồng tại Nhật Bản.",
    "Các chiếc xe buýt này đều là xe tự hành.",
    "",
    "L04_V025",
    "[12227, 13640]",
    "QA",
    "https://youtu.be/7kvm0E6QNkk?t=92",
  ],
  "22": [
    "Cảnh quay trên cao các nhóm người xếp thành nhiều hình chữ nhật ngay ngắn.",
    "Sau đó là cảnh quay bốn người đàn ông mặc đồng phục xanh đang bước đều, trong đó một người vác cờ Việt Nam.",
    "Sau đó là cảnh quay ban chỉ huy đang làm động tác chào.",
    "Được biết đây là buổi Lễ ra quân huấn luyện năm 2024.",
    "L08_V027",
    "[1495, 1800]",
    "QA",
    "https://youtu.be/7kvm0E6QNkk?t=92",
  ],
  "23": [
    "Cảnh quay từ trên cao tại một cảng có rất nhiều container, có một dòng sông và cây cầu.",
    "Sau đó là cảnh quay 2 chiếc cần cẩu màu vàng và 1 cái màu đen.",
    "Sau đó là cảnh quay có 3 chiếc container màu đỏ có chữ Huyndai xếp chồng lên nhau.",
    "Sau đó là cảnh một chiếc container màu đen đang được di chuyển.",
    "L17_V005",
    "[5304, 5503]",
    "QA",
    "https://youtu.be/7kvm0E6QNkk?t=92",
  ],
  "24": [
    "Cảnh quay các em học sinh nữ đang xếp hàng bước vào phòng thi, cô giám thị mặc áo vàng.",
    "Sau đó là cảnh quay có 2 em học sinh nữ mặc đồ thể dục có 2 sọc đỏ trên áo.",
    "Sau đó là cảnh quay trong lớp học các em đang ngồi vào bàn thi, có một em không mặc đồng phục mà mặc áo màu nâu.",
    "Đây là bản tin về Kỳ thi tốt nghiệp THPT 2024.",
    "L18_V027",
    "[1432, 1596]",
    "QA",
    "https://youtu.be/7kvm0E6QNkk?t=92",
  ],
  "25": [
    "Cảnh quay từ phía sau một đoàn đua xe đạp, 2 người cuối mặc áo đỏ và vàng.",
    "Bên trái khung hình là bảng hiệu có chữ 'Thuốc Tây'.",
    "Người mặc áo đỏ có số thứ tự 95.",
    "Sau đó là cận cảnh một người tay đua áo xanh số 11.",
    "L23_V002",
    "[6904, 7679]",
    "QA",
    "https://youtu.be/7kvm0E6QNkk?t=92",
  ],
  "26": [
    "Cảnh quay một bức tranh hình 2 con rùa.",
    "Bên phải là bức tranh hình 2 con phượng hoàng.",
    "Sau đó là cảnh quay một ông thầy đồ đang cầm bức tranh chụp hình cùng các em học sinh.",
    "Sau đó là cảnh quay các em học sinh được hướng dẫn dùng kính thực tế ảo.",
    "L22_V024",
    "[2824, 3044]",
    "QA",
    "https://youtu.be/7kvm0E6QNkk?t=92",
  ],
  "27": [
    "Cảnh quay các tấm pin năng lượng mặt trời trên mái nhà.",
    "Sau đó là cảnh phỏng vấn một người đàn ông mặc áo trắng tên là Bùi Trung Kiên.",
    "Sau đó quay lại cảnh các tấm pin năng lượng mặt trời.",
    "",
    "L22_V013",
    "[7780, 8105]",
    "QA",
    "https://youtu.be/7kvm0E6QNkk?t=92",
  ],
  "28": [
    "Cảnh quay một người đàn ông mặc áo xanh dương nằm trên giường bệnh, ngón cái bị kẹp bởi một thiết bị.",
    "Người đàn ông được một bác sĩ mặc áo xanh lá đưa thiết bị vào miệng.",
    "Sau đó là cảnh máy tính hiển thị hình ảnh nội soi.",
    "Được biết đây là 'Lần đầu tiên ghép thành công khí quản từ người chết não'",
    "L22_V007",
    "[6820, 7025]",
    "QA",
    "https://youtu.be/7kvm0E6QNkk?t=92",
  ],
  "29": [
    "Cảnh quay một nhóm người mặc áo xanh dương đang phát cơm từ thiện.",
    "Trên áo những người đó có hình đóa sen màu vàng.",
    "Tiếp theo là cảnh quay một thau đậu hủ chiên và 2 người cầm hộp cơm.",
    "Trên áo những người này có chữ 'Chùa Liên Hoa'",
    "L22_V004",
    "[6495, 7061]",
    "QA",
    "https://youtu.be/7kvm0E6QNkk?t=92",
  ],
  "30": [
    "Cảnh quay một bác sĩ áo xanh lá đang khám bệnh cho người phụ nữ.",
    "Ngón trỏ người phụ nữ này kẹp bởi thiết bị màu xanh dương.",
    "Sau đó bác sĩ đang xem ảnh chụp X quang lồng ngực.",
    "Sau đó bác sĩ dùng thiết bị nghe nhịp tim người phụ nữ.",
    "L22_V002",
    "[4918, 5221]",
    "QA",
    "https://youtu.be/7kvm0E6QNkk?t=92",
  ],
  "31": [
    "Cảnh quay một người đàn ông mặc áo xanh đen đang nói chuyện với chiếc mic đeo tai.",
    "Sau đó cảnh một người đang lướt điện thoại, trang web có tên 'OpenAI'.",
    "Sau đó là cảnh robot đang nhấp vào hình quả địa cầu.",
    "Sau đó là cảnh phỏng vấn PGS Đinh Ngọc Minh của trường đại học RMIT.",
    "L21_V024",
    "[7168, 7531]",
    "QA",
    "https://youtu.be/7kvm0E6QNkk?t=92",
  ],
  "32": [
    "Cảnh quay một vườn ớt chuông Malaysia.",
    "Có người đàn ông mặc áo đỏ đang hái ớt.",
    "Khu vườn này ở trong nhà kính.",
    "Sau đó có người phụ nữ đeo khẩu trang đội nón vàng tham gia hái ớt.",
    "L21_V009",
    "[3583, 4458]",
    "QA",
    "https://youtu.be/7kvm0E6QNkk?t=92",
  ],
  "33": [
    "Cảnh quay một vườn ớt chuông Malaysia.",
    "Có người đàn ông mặc áo đỏ đang hái ớt.",
    "Khu vườn này ở trong nhà kính.",
    "Sau đó có người phụ nữ đeo khẩu trang đội nón vàng tham gia hái ớt.",
    "L21_V009",
    "[3583, 4458]",
    "QA",
    "https://youtu.be/7kvm0E6QNkk?t=92",
  ],
  "34": [
    "Cảnh quay các công nhân tại xưởng may, có số thứ tự 1, 7, 9, 13, 15.",
    "Các người công nhân mặc đồng phục màu xanh dạ quang.",
    "Sau đó là cảnh quay cận cảnh người đàn ông ở bàn số 19.",
    "Đồ những người này đang may có màu đò đen.",
    "L19_V029",
    "[1775, 2019]",
    "QA",
    "https://youtu.be/7kvm0E6QNkk?t=92",
  ],
  "35": [
    "Cảnh quay các du khách nước ngoài lên chiếc xe khách màu trắng.",
    "Người đi đầu tiên mặc áo trắng, người phụ nữ đi sau mặc váy nâu.",
    "Trên chiếc xe có chữ VIO Travel.",
    ".",
    "L19_V029",
    "[4513, 4590]",
    "QA",
    "https://youtu.be/7kvm0E6QNkk?t=92",
  ],
  "36": [
    "Cảnh quay dĩa dồi trường xào bông hẹ.",
    "Trên bàn ăn có chén cơm và chén nước tương.",
    "Sau đó là quay cận cảnh dồi trường trước khi chế biến và bông hẹ.",
    ".",
    "L26_V120",
    "[327, 634]",
    "QA",
    "https://youtu.be/7kvm0E6QNkk?t=92",
  ],
  "37": [
    "Bản tin về thành tựu trong phẩu thuật Việt Nam",
    "Sau đó là cảnh bệnh nhân lần lượt đưa 2 bàn chân về phía camera",
    "Cảnh quay chuyển đến phòng Khoa ngoại thần kinh",
    "Cuộc phẫu thuật thành công là 2 ca u não lớn",
    "L07_V013",
    "[03096, 03762]",
    "QA",
    "https://www.youtube.com/watch?v=tVQEavCZNZk&t=142s",
  ],
  "38": [
    "Bảng giá đồ ăn trong một cuộc điều tra ở Đà Nẵng",
    "Sau đó là cảnh một thanh tra nói chuyện với một bà bán thịt",
    "Sau đó người thanh tra kiểm tra thịt cá ở trong siêu thị",
    "Sau đó là cảnh một người đẩy xe qua một gian hàng mì ở Lotte Mart",
    "L07_V023",
    "[04344, 05170]",
    "QA",
    "https://www.youtube.com/watch?v=aMIWjvUIMu0&t=230s",
  ],
  "39": [
    "Cảnh một cô giáo mặc áo dài màu hồng đang chỉ trỏ",
    "Cảnh dàn học sinh mặc áo trắng, có nữ sinh đội nón trắng, và nữ sinh mặc áo thể dục",
    "Cảnh một cô giáo hướng dẫn 6 học sinh đọc giấy, có 2 em mặc đồ dân tộc",
    "Sau đó là cảnh một người đàn ông dạy các em học sinh mặc áo phao",
    "L20_V010",
    "[05199, 05952]",
    "QA",
    "https://www.youtube.com/watch?v=dDKjXOYrC0Y&t=189s",
  ],
  "40": [
    "Đoạn quay bắt đầu có 4 người vi phạm bị công an bắt giữ.",
    "Vì bị phạm tội dùng kiếm chặt biển số xe máy rồi khoe lên mạng.",
    "4 người bị bắt giữ có 1 người nhuộm đầu, cảnh quay có 3 chiếc xe máy của 4 người bị bắt",
    "Tiếp theo cảnh quay chú công an cầm 1 cây kiếm.",
    "L22_V024",
    "[21659,22669]",
    "QA",
    "https://www.youtube.com/watch?v=TE5ED6iwn9g&t=874s",
  ],
  "41": [
    "Cảnh quay là 1 buổi biểu diễn lân tại Hà Nội chào mừng 94 năm thành lập Đảng, có 1 con lân đang có người múa và 2 cái đầu lân",
    "Trên cây những cột để lân nhảy lên có những con số màu đen",
    "Người ở trong con lân mặc áo màu đỏ",
    "Có những người mặc áo tím họa tiết hồng đánh trống và gõ chiêng",
    "L24_V021",
    "[00741,10272]",
    "QA",
    "https://www.youtube.com/watch?v=6xfbfbPJFBE&t=33s",
  ],

  "42": [
    "Cảnh quay bắt đầu bằng một người con gái đang lựa mắm cá linh",
    "Được biết đây là cửa hàng của Bà Giáo Khỏe, chuyên làm mắm các loại cá",
    "Cảnh quay tiếp theo có 3 người đang làm mắm",
    "Tiếp theo có một người đàn ông đang xem quy trình sản xuất trên máy tính, và có đoạn quay phỏng vấn người chủ của cửa hàng này",
    "L28_V006",
    "[11799,13233]",
    "QA",
    "https://www.youtube.com/watch?v=yATaJAabU7o&t=471s",
  ],
  "43": [
    "Cảnh quay bắt đầu bằng một người câu cá ở Paris",
    "Người này câu được con cá to nhưng thả đi và không bắt, sau đó bắt 1 con cá nhỏ",
    "Người này đánh giá chất lượng của dòng sông có cải thiện",
    "Kết thúc cảnh quay là cảnh quay 2 con vịt và 2 người đàn ông câu cá",
    "L11_V024",
    "[21545,22575]",
    "QA",
    "https://www.youtube.com/watch?v=XxmM9qU5XaY&t=903s",
  ],
  "44": [
    "Cảnh quay trong một sự kiện ở Thái Lan dành cho những sáng kiến giảm rác thải",
    "Có vài bé nhỏ đang vẽ trên trên giấy hoặc màn hình ipad bằng viết điện tử",
    "Tiếp theo các tác phẩm vẽ này được chiếu xuống 1 con kênh",
    "Con kênh đó có 1 cây cầu bắt ngang và có rất nhiều người đứng xem các tác phẩm",
    "L03_V029",
    "[21377,22463]",
    "QA",
    "https://www.youtube.com/watch?v=AtauGfUS8dg&t=898s",
  ],
  "45": [
    "Cảnh quay bắt đầu có vài người đang chuẩn bị để phóng tên lửa",
    "Sau đó tên lửa được phóng, và có nhiều người từ khắp thế giới đến xem, ví dụ như người từ nước Đức và Anh",
    "Có nhiều người cổ vũ và tắm bùn trong khi xem tên lửa",
    "Sự kiện này tổ chức ở Thái Lan tại 1 vùng đất trống",
    "L16_V014",
    "[21321,23210]",
    "QA",
    "https://www.youtube.com/watch?v=RCslJXvFwKM&t=720s",
  ],
};

export default queries;
