// Define the type for queries object
type QueriesType = {
  [key: string]: string[];
};

// Define your queries object
const queries: QueriesType = {
  "1": [
    "Mở đầu video là cảnh quay tại nút giao giữa 2 con đường với rất nhiều xe máy đang đậu.",
    "Sau đó lần lượt là cảnh quay cận cảnh tới bảng tên đường và các chiếc xe máy.",
    "Tiếp theo là cạnh một người phụ nữ mặc áo tím đang thái thịt bò.",
    "Món ăn người này đang chuẩn bị là món phở bò.",
    "L30_V064",
    "00375",
    "QA",
    "youtubelink",
  ],
  "2": [
    "Mở đầu video là cảnh một người đàn ông mặc áo xanh dương đang để tay trên eo, giữa một lớp học.",
    "Sau đó là cảnh quay người đàn ông này đứng kế các bạn học sinh trong lớp.",
    "Sau đó là cảnh người đàn ông này đứng kế tấm bảng có ghi số 115/110.",
    "Tiếp theo là cảnh quay phỏng vấn trực tiếp người đàn ông này, trên áo có chữ BIO.",
    "L30_V039",
    "00351",
    "QA",
    "...",
  ],
  "3": [
    "Mở đầu video là cảnh một người đàn ông bước vào cánh cửa lớn màu xanh dương.",
    "Sau đó là cảnh người đàn ông này đứng kế một cái bàn với rất nhiều ổ cắm điện.",
    "Sau đó là cảnh người đàn ông này đeo bóng đèn trên trán và đứng giữa căn phòng tối đen.",
    "Được biết đây là tòa nhà mà ông dùng để nuôi yến.",
    "L30_V088",
    "00528",
    "QA",
    "...",
  ],
  "4": [
    "Cảnh một người phụ nữ ngồi trên chiếc thuyền nhỏ màu xanh dương.",
    "Sau đó là cảnh người phụ nữ này hái nấm từ một chiếc bình.",
    "Sau đó xuất hiện thêm một người phụ nữ mặc áo hồng đứng trong khung hình, 2 bên khung hình là các bình đựng nấm.",
    "Cuối cùng là cảnh 2 người phụ nữ này đang phỏng vấn với nhau.",
    "L29_V011",
    "04494",
    "QA",
    "...",
  ],
  "5": [
    "Cảnh quay một người đàn ông đang chụp hình người phụ nữ mặc áo trắng đang trèo thuyền",
    "Sau đó là cảnh nhiều người phụ nữ mặc áo bà ba màu xanh lá đi ngang qua khung hình",
    "Đây là cảnh quay khu du lịch sinh thái với nhiều người đang mặc áo phao.",
    "Sau đó là cảnh 4 người đang trèo thuyền kayak.",
    "L29_V009",
    "03715",
    "QA",
    "...",
  ],
  "6": [
    "Cảnh quay rất nhiều bạn trẻ đang đứng xếp hàng.",
    "Được biết đây là một buổi trình diễn kịch nói của sinh viên.",
    "Sau đó là cảnh quay một chiếc màn hình lơn với dòng chữ 'Sắc Cổ Viễn Xưa'.",
    "Sau đó là cảnh 4 người đang thảo luận, phía sau là màn hình lớn về trang phục và giày dép.",
    "L30_V026",
    "00760",
    "QA",
    "...",
  ],
  "7": [
    "Cảnh quay một cái hồ bơi với rất nhiều trẻ con.",
    "Sau đó là cảnh quay một người đàn ông đội nón vàng, đang hướng dẫn đứa trẻ học bơi.",
    "Sau đó là cảnh quay các đứa trẻ đang đứng khởi động.",
    "Được biết đây là một buổi học của lớp dạy bơi miễn phí.",
    "L30_V049",
    "00397",
    "QA",
    "...",
  ],
  "8": [
    "Cảnh quay một chồng sách với thứ tự trên xuống dưới là 5, 7, 11.",
    "Sau đó là cảnh quay một cuốn tập trắng với nhiều chữ chằng chịt.",
    "Sau đó là cảnh quay người phụ nữ là chủ của các cuốn sách này.",
    "Được biết đây là 15 tập nhật kí lưu giữ ký ức.",
    "L30_V027",
    "00474",
    "QA",
    "...",
  ],
  "9": [
    "Cảnh quay một nhóm người mặc áo dài đang khiêng đồ vật màu đỏ.",
    "Những người đàn ông mặc áo dài xanh và phụ nữ mặc áo dài đỏ.",
    "Sau đó là cảnh quay một người nông dân đội nón xanh lá đang gặt lúa nước.",
    "Sau đó là cảnh quay một khu vực đang phơi cá.",
    "L29_V014",
    "01215",
    "QA",
    "...",
  ],
  "11": [
    "Bản tin về buổi triển lãm các bức tranh của một nhân vật nổi tiếng người Anh. Các bức tranh được trưng bày chủ yếu là tranh ký hoạ. Có thể thấy một người đàn ông mặc áo đen đang đứng trước một bức tranh vẽ về bầu trời.",
    "Có ba chiếc máy bay trong bức tranh đó, trong đó có một chiếc máy bay màu đỏ, một chiếc máy bay có cờ Pháp ở đuôi.",
    "Sau đó là một bức tranh vẽ về con người và rô bốt.",
    "Có một bức vẽ về cảnh phim nổi tiếng trong một bộ phim mà ông làm đạo diễn. Triễn lãm này có tên: 'Nghệ thuật của Cameron'",
    "L14_V004",
    "[20250, 20696]",
    "QA",
    "youtubelink",
  ],
  "12": [
    "Các nguyên liệu nấu ăn được đặt trong các dĩa màu trắng bày ở trên bàn, đậy lại bằng cái chén màu xanh ngọc bích.",
    "Nguyên liệu đầu tiên được hé mở là tôm sú, ở vị trí chính giữa, hàng trên. ",
    "Có tổng cộng 6 nguyên liệu tất cả, nguyên liệu thứ 2 được hé lộ là nấm rơm.",
    "Nguyên liệu thứ 3 là cà rốt và củ cải trắng, ở vị trí phía bên trái dĩa tôm sú. Lần lượt có 3 con tôm sú, 6 cái nấm rơm, 1 cà rốt và 1 củ cải trắng.",
    "L26_V433",
    "[00717, 00899]",
    "",
    "",
  ],
  "13": [
    "Cảnh quay một lớp học tình thương, có 3 bạn học sinh mặc áo màu tím, màu kem, màu đỏ theo thứ tự từ trái qua phải.",
    "Máy quay chuyển cảnh đến một bạn nữ mặc áo màu hồng đang sử dụng máy tính cầm tay.",
    "Người thầy giáo mặc áo polo màu xanh, cổ áo màu trắng xanh, tay áo viền màu đỏ, trắng, xanh, đang chỉ tay lên bảng. ",
    "Đây là một lớp học môn toán.",
    "L30_V039",
    "[00673, 01055]",
    "",
    "",
  ],
  "14": [
    "Đầu bếp đang làm gia vị để ướp cho món sườn heo. Đầu tiên ông cho 1/2 muỗng cà phê tiêu vào trong một cái tô thuỷ tinh trong suốt.",
    "Tiếp đến là một muỗng đường, một muỗng canh hạt nêm heo, nước mắm, sa tế, chao.",
    "Sau đó ông trộn đều các loại gia vị với nhau thành một hỗn hợp có màu đỏ.",
    "Tiếp đến là cho sườn vào đảo đều với gia vị. Trên bếp còn có các loại nguyên liệu khác như rau thơm và một trái dừa.",
    "L26_V027",
    "[02013, 03296]",
    "",
    "",
  ],
  "15": [
    "Các lát cá đang được xào với xả trong một chiếc chảo, ở góc trên bên trái khung hình có nấm kim châm.",
    "Cá đã được ướp sẵn với một loại gia vị có màu bột nghệ.",
    "Có thể thấy 8 lát cá tổng cộng",
    "Chiếc chảo nấu cá có màu đen, đang được đặt trên bếp ga.",
    "L26_V402",
    "[03538, 03568]",
    "",
    "",
  ],
  "16": [
    "Một đĩa thức ăn gồm có 3 cái bánh rán, 1 quả trứng gà chiên và thịt heo.",
    "Ở giữa có một ít rau mầm để trang trí.",
    "Có thể thấy các loại nguyên liệu khác, bao gồm trứng gà, bắp hột và xúc xích thái hạt lựu.",
    "Cái dĩa được để trên một chiếc khăn màu trắng.",
    "L26_V191",
    "[06659, 06704]",
    "",
    "",
  ],
  "17": [
    "Cảnh quay từ trên cao một cuộc đua xe đạp giành cho nữ. Có 3 tay đua xuất hiện trong hình.",
    "Tay đua vị trí thứ ba lần lượt vượt qua hai đối thủ còn lại để về đích đầu tiên.",
    "Đoạn này các tay đua đang tăng tốc khi gần về đến đích, tay đua về đích đầu tiên mặc áo màu xanh đậm",
    "Tay đua về nhì mặc áo vàng, khoảng cách giữa người về nhất và về nhì rất sít sao và phải cần đến camera chậm để xác định người về đầu tiên.",
    "L21_V015",
    "[35620, 36170]",
    "",
    "",
  ],
  "18": [
    "Bản tin về lễ rước đuốc Olympic Paris 2024 tại thành phố Marseille, quy tụ nhiều nhân vật nổi tiếng.",
    "Người nhận lửa cuối cùng là Didier Drogba, cựu cầu thủ bóng đá nổi tiếng, anh nhận lửa từ trong sân vận động thành phố.",
    "Sau đó anh chạy ra ngoài qua một con đường có nhiều người hâm mộ vây quanh.",
    "Cuối cùng anh đốt lửa ở chảo lửa bên ngoài sân vận động. ",
    "L16_V010",
    "[28835, 29156]",
    "",
    "",
  ],
  "19": [
    "Cảnh một buổi diễn nghệ thuật tại một nhà hát nổi tiếng ở Việt Nam, phía sau phông nền là hình ảnh một toà lâu đài cổ, xung quanh có các cây lá kim cao.",
    "Có một chiếc cầu thang lớn dẫn vào lâu đài.",
    "Các vũ công nam mặc áo màu đỏ, quần màu trắng, biểu diễn cùng các vũ công nữ theo từng cặp.",
    "Đây là bản tin vở diễn Hồ Thiên Nga của Nhà hát kịch Việt Nam tại Hà Nội.",
    "L17_V021",
    "[11375, 11566]",
    "",
    "",
  ],
  "20": [
    "Một người phụ nữ mặc áo màu trắng đi trong một vườn dâu.",
    "Có một người đàn ông mặc áo màu đỏ ban đầu đi bên phải người phụ nữ.",
    "Người phụ nữ đeo khăn quàng cổ màu đỏ, trên áo có một hình thêu trái tim có màu đỏ.",
    "Cuối bản tin là cảnh người đàng ông và người phụ nữ cùng đi qua chiếc cầu khỉ.",
    "L27_V015",
    "[05944, 06418]",
    "",
    "",
  ],
};

export default queries;